<ul class="actionList">
    <li><a href="<?=$this->url(array('action' => 'index', 'id' => null))?>"><?=$this->translate->_('Edit configuration')?></a></li>
    <li><a href="<?=$this->url(array('action' => 'users', 'id' => null))?>"><?=$this->translate->_('Edit users')?></a></li>
    <li><a href="<?=$this->url(array('action' => 'skins', 'id' => null))?>"><?=$this->translate->_('Edit skins')?></a></li>
    <li><a href="<?=$this->url(array('action' => 'languages', 'id' => null))?>"><?=$this->translate->_('Edit languages')?></a></li>
</ul>
