<ul class="actionList">
    <li><a href="<?=$this->url(array('action' => 'view'))?>"><?=$this->translate->_('View server details')?></a></li>
    <li><a href="<?=$this->url(array('action' => 'reboot'))?>"><?=$this->translate->_('Reboot this server')?></a></li>
    <li><a href="<?=$this->url(array('action' => 'viewSensors'))?>"><?=$this->translate->_('View hardware sensors')?></a></li>
    <!-- <li><a href="#"><?=$this->translate->_('Boot rescue environment')?></a></li>
    <li><a href="#"><?=$this->translate->_('Perform a hardware test')?></a></li>
    <li><a href="#"><?=$this->translate->_('Perform a security test')?></a></li> -->
</ul>

